msp430: fix dadd operation and types for .b instructions
Fixes assertion errors in vex_helper.py, e.g. below:

AssertionError: operation needs to be well typed: Xor16(t6,t9)
types: t0:Ity_I16 t1:Ity_I16 t2:Ity_I16 t3:Ity_I8 t4:Ity_I16 t5:Ity_I16 t6:Ity_I16
t7:Ity_I8 t8:Ity_I8 t9:Ity_I8